// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZzio5kU99SP4h10QKgB4-3KK-toNkOjM',
    appId: '1:1027352102596:web:65068b19c34c6c59d4eb91',
    messagingSenderId: '1027352102596',
    projectId: 'tiktok-sigi',
    authDomain: 'tiktok-sigi.firebaseapp.com',
    storageBucket: 'tiktok-sigi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFUzmcfZ1x99tKblNEIIpKbLcKQP5uuCg',
    appId: '1:1027352102596:android:7c8648a2062e4b0cd4eb91',
    messagingSenderId: '1027352102596',
    projectId: 'tiktok-sigi',
    storageBucket: 'tiktok-sigi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhQ6jSOI1CSM_56WDlbztlsMlkdV8m5LA',
    appId: '1:1027352102596:ios:064d818cecd27d2ed4eb91',
    messagingSenderId: '1027352102596',
    projectId: 'tiktok-sigi',
    storageBucket: 'tiktok-sigi.firebasestorage.app',
    iosBundleId: 'com.example.twitterChallenge',
  );

}